version: '3.8'

services:
  # GraphDB Service
  graphdb:
    image: ontotext/graphdb:10.7.6
    container_name: graphdb
    ports:
      - "7200:7200" # GraphDB Workbench and REST API
      - "7300:7300" # GraphDB Triplestore Protocol (TSP)
    volumes:
      # Persistent volume for GraphDB data
      - graphdb_data:/opt/graphdb/home/data
      # Mount a local directory for importing files into GraphDB
      - ./docker-import:/opt/graphdb/import
    restart: unless-stopped
    networks:
      - my_app_network # Connect to a custom network for inter-service communication
